// <auto-generated />
using System;
using App.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace App.Migrations
{
    [DbContext(typeof(OttoDbContext))]
    partial class OttoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("App.Models.CommentPosition", b =>
                {
                    b.Property<int>("KommentarId")
                        .HasColumnType("int");

                    b.Property<string>("BorderColor")
                        .HasColumnType("longtext");

                    b.Property<float>("XPosition")
                        .HasColumnType("float");

                    b.Property<float>("YPosition")
                        .HasColumnType("float");

                    b.HasKey("KommentarId");

                    b.ToTable("CommentPositions");
                });

            modelBuilder.Entity("App.Models.FileModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("BlobStorageUri")
                        .HasColumnType("longtext");

                    b.Property<string>("FileName")
                        .HasColumnType("longtext");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("FileType")
                        .HasColumnType("longtext");

                    b.Property<int?>("ForschungsfrageId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("UploadDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ID");

                    b.HasIndex("ForschungsfrageId");

                    b.ToTable("files");
                });

            modelBuilder.Entity("App.Models.Forschungsfrage", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("forschungsfragen");
                });

            modelBuilder.Entity("App.Models.Kommentar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ParentKommentarId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ParentKommentarId");

                    b.ToTable("Kommentare");
                });

            modelBuilder.Entity("App.Models.MediaPosition", b =>
                {
                    b.Property<int>("FileModelId")
                        .HasColumnType("int");

                    b.Property<float>("XPosition")
                        .HasColumnType("float");

                    b.Property<float>("YPosition")
                        .HasColumnType("float");

                    b.HasKey("FileModelId");

                    b.ToTable("MediaPositions");
                });

            modelBuilder.Entity("App.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("App.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("App.Models.CommentPosition", b =>
                {
                    b.HasOne("App.Models.Kommentar", "Kommentar")
                        .WithMany("CommentPositions")
                        .HasForeignKey("KommentarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kommentar");
                });

            modelBuilder.Entity("App.Models.FileModel", b =>
                {
                    b.HasOne("App.Models.Forschungsfrage", "Forschungsfrage")
                        .WithMany("Files")
                        .HasForeignKey("ForschungsfrageId");

                    b.Navigation("Forschungsfrage");
                });

            modelBuilder.Entity("App.Models.Kommentar", b =>
                {
                    b.HasOne("App.Models.Kommentar", "ParentKommentar")
                        .WithMany("Replies")
                        .HasForeignKey("ParentKommentarId");

                    b.Navigation("ParentKommentar");
                });

            modelBuilder.Entity("App.Models.MediaPosition", b =>
                {
                    b.HasOne("App.Models.FileModel", "FileModel")
                        .WithMany("MediaPositions")
                        .HasForeignKey("FileModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FileModel");
                });

            modelBuilder.Entity("App.Models.FileModel", b =>
                {
                    b.Navigation("MediaPositions");
                });

            modelBuilder.Entity("App.Models.Forschungsfrage", b =>
                {
                    b.Navigation("Files");
                });

            modelBuilder.Entity("App.Models.Kommentar", b =>
                {
                    b.Navigation("CommentPositions");

                    b.Navigation("Replies");
                });
#pragma warning restore 612, 618
        }
    }
}
